export { default as grave} from './grave.jpg'
export { default as moher} from './moher.jpg'
export { default as island} from './island.jpg'
export { default as canyon } from './canyon.jpg'
export { default as cliff } from './cliff.jpg'

export { default as sun } from './sun-art.jpeg'
export { default as skeleton } from './skeleton-art.jpeg'
export { default as skull } from './skull-art.jpeg'
export { default as wowsky } from './wowskypic.png'
export { default as sandy } from './sandy.png'
export { default as moonsky } from './moonysky.png'
export { default as purple } from './purple-art.jpeg'
export { default as wild } from './wild.jpeg'